# Generated by Django 4.2.6 on 2023-12-03 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carroceria', models.CharField()),
                ('carro_detalle', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainciotrabajo', models.DateField()),
                ('experiencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tramite', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_estado', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasemana', models.CharField()),
                ('horaincio', models.TimeField()),
                ('horafino', models.TimeField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField()),
                ('apellidos', models.CharField()),
                ('direccion', models.CharField()),
                ('telefono', models.IntegerField(unique=True)),
                ('email', models.CharField(unique=True)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ciudad')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Propetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_afiliacion', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoterminal', models.CharField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ciudad')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField()),
                ('cilindraje', models.IntegerField()),
                ('numerochasis', models.IntegerField(unique=True)),
                ('modelo', models.CharField()),
                ('kilogramos', models.IntegerField()),
                ('linea', models.CharField()),
                ('id_carroceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.carroceria')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.color')),
                ('id_documentovehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.documentovehiculo')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.marca')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.propetario')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ruta')),
                ('id_termina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventafecha', models.DateField()),
                ('totalneto', models.FloatField()),
                ('totalbruto', models.FloatField()),
                ('procentajedescuento', models.FloatField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ruta')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_rol', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiqvehiculo', models.CharField()),
                ('puesto', models.IntegerField()),
                ('totalbruto', models.FloatField()),
                ('iva', models.FloatField()),
                ('totalmasiva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cliente')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.usuario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.venta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.CreateModel(
            name='RutaCiudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoparada', models.IntegerField()),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ciudad')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaasignaconductor', models.DateField()),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.conductor')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.horario')),
            ],
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado'),
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='id_tipodocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tipodocumento'),
        ),
        migrations.CreateModel(
            name='DocumentoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.IntegerField()),
                ('categoria_documento', models.CharField()),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.tipodocumento')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.vehiculo'),
        ),
        migrations.AddField(
            model_name='color',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.persona'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.departamento'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado'),
        ),
        migrations.AddField(
            model_name='carroceria',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.estado'),
        ),
    ]
